TextConsoleRPG/Monster.cs
=> feat: Add Monster Class

TextConsoleRPG/Item.cs, TextConsoleRPG/Program.cs
=> feat: set name, job

TextConsoleRPG/Program.cs
=> fix: Fix 아이템DB 삭제

TextConsoleRPG/Program.cs
=> feat: Add load

TextConsoleRPG/Monster.cs, TextConsoleRPG/Program.cs
=> 공격 오차 범위 설정

TextConsoleRPG/Monster.cs, TextConsoleRPG/Program.cs
=> feat: Add StartBattle

TextConsoleRPG/Character.cs, TextConsoleRPG/MonsterManager.cs, TextConsoleRPG/Program.cs
적 턴, 전투결과, 함수이름 변경, 몬스터매니저클래스 추가 등
=> feat: Add EnemyPhase, BattleResult

TextConsoleRPG/Character.cs, TextConsoleRPG/Monster.cs, TextConsoleRPG/Program.cs, TextConsoleRPG/Skills.cs
=> feat: Add Skill

TextConsoleRPG/Program.cs
=> fix: Fix Skill

TextConsoleRPG/Character.cs, TextConsoleRPG/Item.cs, TextConsoleRPG/Program.cs, TextConsoleRPG/Quest.cs
-아이템 표시 기능 수정
-플레이어 아이템 정보 저장/불러오기 추가
=> Quest 보상 클래스 분리 작업

TextConsoleRPG/MonsterManager.cs
=> docs: Add Monster

TextConsoleRPG/Character.cs, TextConsoleRPG/LevelManager.cs, TextConsoleRPG/Monster.cs, TextConsoleRPG/MonsterManager.cs, TextConsoleRPG/Program.cs
=> feat: Add Potion

TextConsoleRPG/Character.cs, TextConsoleRPG/Item.cs, TextConsoleRPG/Monster.cs, TextConsoleRPG/MonsterManager.cs, TextConsoleRPG/Program.cs
전투에서 이길 시 보상획득 시스템 구현
그에 맞게 몬스터 클래스 수정
=> feat: Add Reward

TextConsoleRPG/Character.cs, TextConsoleRPG/Monster.cs, TextConsoleRPG/PartyManager.cs, TextConsoleRPG/PartyMember.cs, TextConsoleRPG/Player.cs, TextConsoleRPG/Program.cs, TextConsoleRPG/Quest.cs, TextConsoleRPG/Skills.cs
=> feat: Party Member

TextConsoleRPG/Character.cs, TextConsoleRPG/MonsterManager.cs, TextConsoleRPG/Program.cs, TextConsoleRPG/StageManager.cs
스테이지선택
전투 승리시 다음 스테이지 해금
플레이어 방어력 만큼 몬스터가 받는 데미지 감소되는 현상 수정
=> 스테이지+방어력 오류 수정

TextConsoleRPG/Player.cs, TextConsoleRPG/Program.cs, TextConsoleRPG/Quest.cs
-플레이어 데이터 파일에 퀘스트 리스트 넣는 작업 필요
=> 퀘스트 완료 및 보상 수령 1차 테스트 완료

TextConsoleRPG/Character.cs, TextConsoleRPG/Player.cs, TextConsoleRPG/Program.cs, TextConsoleRPG/Quest.cs
=> 퀘스트 저장/불러오기 기능 추가

TextConsoleRPG/Character.cs, TextConsoleRPG/Item.cs
똑같은 종류의 장착 아이템을 착용하려고 할 시 기존 장착된 아이템 해제 및 기존 장비의 스텟 보정값 제거
=> Feat : 중복 아이템 해제

TextConsoleRPG/Character.cs, TextConsoleRPG/PartyManager.cs, TextConsoleRPG/Program.cs
함수종료시 리턴하여 메인메뉴UI로 돌아가는 방식으로 변경
=> Refactor: refactor

TextConsoleRPG/Character.cs, TextConsoleRPG/Program.cs
=> Fix: Attack Fix

TextConsoleRPG/Character.cs, TextConsoleRPG/PartyManager.cs, TextConsoleRPG/Program.cs
=> Fix: UI return

TextConsoleRPG/Program.cs
=> Fix: PartyMember Skills

TextConsoleRPG/Program.cs
=> Fix: party skill

TextConsoleRPG/Program.cs
=> Fix: PartyPhase

TextConsoleRPG/Program.cs
=> Fix: Party result

TextConsoleRPG/Program.cs
=> Update Program.cs - 데이터 파일 경로 수정
